services:
  rabbitmq:
    build:
      context: ./src/cmd/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    environment:
      - RABBITMQ_LOG_LEVELS=error
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit vm_memory_high_watermark 0.4
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
      - 5672:5672
      - 15672:15672
    logging:
      driver: "none"

  gateway:
    build:
      context: ./src/
      dockerfile: cmd/gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ACCOUNT_QUEUES=filter_account_id_0,filter_account_id_1
      - TRANSFERS_EXCHANGE=transfers_exchange
      - TRANSFERS_ROUTING_KEYS=TRANSFERS_Q5_KEY,TRANSFERS_Q1234_KEY
      - RESULTS_QUEUE=results_queue
      - MOM_HOST=rabbitmq
      - MOM_PORT=5672
      - SERVER_HOST=gateway
      - SERVER_PORT=5678
      - QUERY_EOFS_EXPECTED=1:1,2:2,3:1,4:2,5:1

  client_0:
    build:
      context: ./src/
      dockerfile: cmd/client/Dockerfile
    container_name: client_0
    depends_on:
      - gateway
    environment:
      - SERVER_HOST=gateway
      - SERVER_PORT=5678
      - INPUT_FILE_ACCOUNTS=/input/accounts_0.csv
      - INPUT_FILE_TRANS=/input/transactions_0.csv
      - OUTPUT_FILE_PREFIX=/output/output_0
      - MAX_BATCH_SIZE=1000
      - LOG_LEVEL=DEBUG
    volumes:
      - ./input:/input
      - ./output:/output

  client_1:
    build:
      context: ./src/
      dockerfile: cmd/client/Dockerfile
    container_name: client_1
    depends_on:
      - gateway
    environment:
      - SERVER_HOST=gateway
      - SERVER_PORT=5678
      - INPUT_FILE_ACCOUNTS=/input/accounts_1.csv
      - INPUT_FILE_TRANS=/input/transactions_1.csv
      - OUTPUT_FILE_PREFIX=/output/output_1
      - MAX_BATCH_SIZE=1000
      - LOG_LEVEL=DEBUG
    volumes:
      - ./input:/input
      - ./output:/output

  # Query 1

  filter_currency_0:
    build:
      context: ./src/
      dockerfile: cmd/filter/Dockerfile
    container_name: filter_currency_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ID=0
      - MOM_PORT=5672
      - MOM_HOST=rabbitmq
      - INPUT_EXCHANGE=transfers_exchange
      - INPUT_QUEUE=transfers_queue_q1234
      - INPUT_ROUTING_KEYS=TRANSFERS_Q1234_KEY
      - OUTPUT_EXCHANGE=filtered_transfers_exchange
      - OUTPUT_QUEUE=filtered_transfers_q
      - OUTPUT_ROUTING_KEYS=falopa
      - CURRENCIES=US Dollar
      - FILTER_TYPE=CURRENCY
      - FILTER_AMOUNT=2
      - QUERY_ID=1
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  filter_currency_1:
    build:
      context: ./src/
      dockerfile: cmd/filter/Dockerfile
    container_name: filter_currency_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ID=1
      - MOM_PORT=5672
      - MOM_HOST=rabbitmq
      - INPUT_EXCHANGE=transfers_exchange
      - INPUT_QUEUE=transfers_queue_q1234
      - INPUT_ROUTING_KEYS=TRANSFERS_Q1234_KEY
      - OUTPUT_EXCHANGE=filtered_transfers_exchange
      - OUTPUT_QUEUE=filtered_transfers_q
      - OUTPUT_ROUTING_KEYS=falopa
      - CURRENCIES=US Dollar
      - FILTER_TYPE=CURRENCY
      - FILTER_AMOUNT=2
      - QUERY_ID=1
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  filter_amount_0:
    build:
      context: ./src/
      dockerfile: cmd/filter/Dockerfile
    container_name: filter_amount_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ID=0
      - MOM_PORT=5672
      - MOM_HOST=rabbitmq
      - INPUT_EXCHANGE=filtered_transfers_exchange
      - INPUT_QUEUE=filtered_transfers_q
      - INPUT_ROUTING_KEYS=falopa
      - OUTPUT_EXCHANGE=results_queue
      - OUTPUT_QUEUE=results_queue
      - OUTPUT_ROUTING_KEYS=falopa2
      - AMOUNT=50.0
      - FILTER_TYPE=AMOUNT
      - FILTER_AMOUNT=2
      - QUERY_ID=1
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  filter_amount_1:
    build:
      context: ./src/
      dockerfile: cmd/filter/Dockerfile
    container_name: filter_amount_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ID=1
      - MOM_PORT=5672
      - MOM_HOST=rabbitmq
      - INPUT_EXCHANGE=filtered_transfers_exchange
      - INPUT_QUEUE=filtered_transfers_q
      - INPUT_ROUTING_KEYS=falopa
      - OUTPUT_EXCHANGE=results_queue
      - OUTPUT_QUEUE=results_queue
      - OUTPUT_ROUTING_KEYS=falopa2
      - AMOUNT=50.0
      - FILTER_TYPE=AMOUNT
      - FILTER_AMOUNT=2
      - QUERY_ID=1
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  # Query 2

  reducer_q2_0:
    build:
      context: ./src/
      dockerfile: cmd/reducer/Dockerfile
    container_name: reducer_q2_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ID=0
      - REDUCER_AMOUNT=2
      - MOM_HOST=rabbitmq
      - MOM_PORT=5672
      - INPUT_EXCHANGE=filtered_transfers_exchange
      - INPUT_QUEUE=reducer_q2_in_q
      - INPUT_ROUTING_KEYS=falopa
      - OUTPUT_QUEUES=reduced_transfers_q2_0,reduced_transfers_q2_1
      - OUTPUT_ROUTING_KEYS=falopa
      - QUERY_ID=2
      - INPUT_EOFS_EXPECTED=2
      - REDUCER_TYPE=MAX_AMOUNT_FROM_BANK
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  reducer_q2_1:
    build:
      context: ./src/
      dockerfile: cmd/reducer/Dockerfile
    container_name: reducer_q2_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ID=1
      - REDUCER_AMOUNT=2
      - MOM_HOST=rabbitmq
      - MOM_PORT=5672
      - INPUT_EXCHANGE=filtered_transfers_exchange
      - INPUT_QUEUE=reducer_q2_in_q
      - INPUT_ROUTING_KEYS=falopa
      - OUTPUT_QUEUES=reduced_transfers_q2_0,reduced_transfers_q2_1
      - OUTPUT_ROUTING_KEYS=falopa
      - QUERY_ID=2
      - INPUT_EOFS_EXPECTED=2
      - REDUCER_TYPE=MAX_AMOUNT_FROM_BANK
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  filter_account_id_already_seen_0:
    build:
      context: ./src/
      dockerfile: cmd/filter/Dockerfile
    container_name: filter_account_id_already_seen_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - MOM_HOST=rabbitmq
      - MOM_PORT=5672
      - ID=1
      - INPUT_QUEUE=filter_account_id_0
      - OUTPUT_QUEUES=join_q2_accounts_q_0,join_q2_accounts_q_1
      - FILTER_AMOUNT=2
      - FILTER_TYPE=BANK_DISTINCT
      - QUERY_ID=2

  filter_account_id_already_seen_1:
    build:
      context: ./src/
      dockerfile: cmd/filter/Dockerfile
    container_name: filter_account_id_already_seen_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - MOM_HOST=rabbitmq
      - MOM_PORT=5672
      - ID=1
      - INPUT_QUEUE=filter_account_id_1
      - OUTPUT_QUEUES=join_q2_accounts_q_0,join_q2_accounts_q_1
      - FILTER_AMOUNT=2
      - FILTER_TYPE=BANK_DISTINCT
      - QUERY_ID=2

  join_q2_0:
    build:
      context: ./src/
      dockerfile: cmd/join/Dockerfile
    container_name: join_q2_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - MOM_HOST=rabbitmq
      - MOM_PORT=5672
      - JOIN_TYPE=transfer_account_by_bank
      - LEFT_INPUT_QUEUE=reduced_transfers_q2_0
      - RIGHT_INPUT_QUEUE=join_q2_accounts_q_0
      - OUTPUT_EXCHANGE=results_queue
      - OUTPUT_QUEUE=results_queue
      - OUTPUT_ROUTING_KEYS=falopa2
      - LEFT_EOFS_EXPECTED=2
      - RIGHT_EOFS_EXPECTED=2
      - JOIN_AMOUNT=2
      - ID=0

  join_q2_1:
    build:
      context: ./src/
      dockerfile: cmd/join/Dockerfile
    container_name: join_q2_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - MOM_HOST=rabbitmq
      - MOM_PORT=5672
      - JOIN_TYPE=transfer_account_by_bank
      - LEFT_INPUT_QUEUE=reduced_transfers_q2_1
      - RIGHT_INPUT_QUEUE=join_q2_accounts_q_1
      - OUTPUT_EXCHANGE=results_queue
      - OUTPUT_QUEUE=results_queue
      - OUTPUT_ROUTING_KEYS=falopa2
      - LEFT_EOFS_EXPECTED=2
      - RIGHT_EOFS_EXPECTED=2
      - JOIN_AMOUNT=2
      - ID=1
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  filter_and_splitter_q4_0:
    build:
      context: ./src/
      dockerfile: cmd/filterandsplitter/Dockerfile
    container_name: filter_and_splitter_q4_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ID=0
      - MOM_HOST=rabbitmq
      - MOM_PORT=5672
      - FILTER_AMOUNT=2
      - OUTPUT_AMOUNT=2
      - OUTPUT_MIDDLEWARE_PREFIX=filter_splitter_q4
      - INPUT_EXCHANGE=transfers_exchange
      - INPUT_QUEUE=transfers_q4_queue
      - INPUT_ROUTING_KEYS=TRANSFERS_Q1234_KEY
      - "DATE_RANGE=2000-01-01 00:00:00,2030-01-01 00:00:00"
      - QUERY_ID=4
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  filter_and_splitter_q4_1:
    build:
      context: ./src/
      dockerfile: cmd/filterandsplitter/Dockerfile
    container_name: filter_and_splitter_q4_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ID=1
      - MOM_HOST=rabbitmq
      - MOM_PORT=5672
      - FILTER_AMOUNT=2
      - OUTPUT_AMOUNT=2
      - OUTPUT_MIDDLEWARE_PREFIX=filter_splitter_q4
      - INPUT_EXCHANGE=transfers_exchange
      - INPUT_QUEUE=transfers_q4_queue
      - INPUT_ROUTING_KEYS=TRANSFERS_Q1234_KEY
      - "DATE_RANGE=2000-01-01 00:00:00,2030-01-01 00:00:00"
      - QUERY_ID=4
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  join_accounts_q4_0:
    build:
      context: ./src/
      dockerfile: cmd/joinaccounts/Dockerfile
    container_name: join_accounts_q4_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ID=0
      - MOM_HOST=rabbitmq
      - MOM_PORT=5672
      - OUTPUT_AMOUNT=2
      - OUTPUT_MIDDLEWARE_PREFIX=join_accounts_q4
      - INPUT_MIDDLEWARE_PREFIX=filter_splitter_q4
      - QUERY_ID=4
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  join_accounts_q4_1:
    build:
      context: ./src/
      dockerfile: cmd/joinaccounts/Dockerfile
    container_name: join_accounts_q4_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ID=1
      - MOM_HOST=rabbitmq
      - MOM_PORT=5672
      - OUTPUT_AMOUNT=2
      - OUTPUT_MIDDLEWARE_PREFIX=join_accounts_q4
      - INPUT_MIDDLEWARE_PREFIX=filter_splitter_q4
      - QUERY_ID=4
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  acum_accounts_q4_0:
    build:
      context: ./src/
      dockerfile: cmd/acumaccounts/Dockerfile
    container_name: acum_accounts_q4_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ID=0
      - MOM_HOST=rabbitmq
      - MOM_PORT=5672
      - OUTPUT_AMOUNT=2
      - OUTPUT_MIDDLEWARE_PREFIX=acum_accounts_q4
      - INPUT_MIDDLEWARE_PREFIX=join_accounts_q4
      - EXPECTED_EOFS=2
      - REQUIRED_AMT=2
      - QUERY_ID=4
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  acum_accounts_q4_1:
    build:
      context: ./src/
      dockerfile: cmd/acumaccounts/Dockerfile
    container_name: acum_accounts_q4_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ID=1
      - MOM_HOST=rabbitmq
      - MOM_PORT=5672
      - OUTPUT_AMOUNT=2
      - OUTPUT_MIDDLEWARE_PREFIX=acum_accounts_q4
      - INPUT_MIDDLEWARE_PREFIX=join_accounts_q4
      - EXPECTED_EOFS=2
      - REQUIRED_AMT=2
      - QUERY_ID=4
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  filter_account_seen_q4_0:
    build:
      context: ./src/
      dockerfile: cmd/filteraccountseen/Dockerfile
    container_name: filter_account_seen_q4_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ID=0
      - MOM_HOST=rabbitmq
      - MOM_PORT=5672
      - INPUT_MIDDLEWARE_PREFIX=acum_accounts_q4
      - OUTPUT_MIDDLEWARE=results_queue
      - EXPECTED_EOFS=2
      - QUERY_ID=4
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  filter_account_seen_q4_1:
    build:
      context: ./src/
      dockerfile: cmd/filteraccountseen/Dockerfile
    container_name: filter_account_seen_q4_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - ID=1
      - MOM_HOST=rabbitmq
      - MOM_PORT=5672
      - INPUT_MIDDLEWARE_PREFIX=acum_accounts_q4
      - OUTPUT_MIDDLEWARE=results_queue
      - EXPECTED_EOFS=2
      - QUERY_ID=4
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"

  # Query 5

  filter_date_and_payment_0:
    build:
      context: ./src/
      dockerfile: cmd/filter/Dockerfile
    container_name: filter_date_and_payment_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - MOM_HOST=rabbitmq
      - MOM_PORT=5672
      - ID=0
      - INPUT_EXCHANGE=transfers_exchange
      - INPUT_ROUTING_KEYS=TRANSFERS_Q5_KEY
      - INPUT_QUEUE=transfers_queue_q5
      - OUTPUT_EXCHANGE=filtered_date_and_payment_exchange
      - OUTPUT_ROUTING_KEYS=TRANSFERS_Q5_KEY
      - FILTER_AMOUNT=2
      - FILTER_TYPE=DATE_RANGE_AND_PAYMENT
      - DATE_RANGE=2022-09-01 00:00:00,2022-09-06 00:00:00
      - PAYMENT_FORMATS=ACH,Wire
      - QUERY_ID=5

  filter_date_and_payment_1:
    build:
      context: ./src/
      dockerfile: cmd/filter/Dockerfile
    container_name: filter_date_and_payment_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - MOM_HOST=rabbitmq
      - MOM_PORT=5672
      - ID=1
      - INPUT_EXCHANGE=transfers_exchange
      - INPUT_ROUTING_KEYS=TRANSFERS_Q5_KEY
      - INPUT_QUEUE=transfers_queue_q5
      - OUTPUT_EXCHANGE=filtered_date_and_payment_exchange
      - OUTPUT_ROUTING_KEYS=TRANSFERS_Q5_KEY
      - FILTER_AMOUNT=2
      - FILTER_TYPE=DATE_RANGE_AND_PAYMENT
      - DATE_RANGE=2022-09-01 00:00:00,2022-09-06 00:00:00
      - PAYMENT_FORMATS=ACH,Wire
      - QUERY_ID=5

  fetcher:
    build:
      context: ./src/
      dockerfile: cmd/fetcher/Dockerfile
    container_name: fetcher
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - MOM_HOST=rabbitmq
      - MOM_PORT=5672
      - INPUT_QUEUE=filtered_transfers_q5_fetcher
      - INPUT_EXCHANGE=filtered_date_and_payment_exchange
      - INPUT_ROUTING_KEYS=TRANSFERS_Q5_KEY
      - OUTPUT_QUEUES=fetcher_output_0,fetcher_output_1
      - QUERY_ID=5
      - QUOTE=USD
    
  filter_amt_q5_0:
    build:
      context: ./src/
      dockerfile: cmd/filter/Dockerfile
    container_name: filter_amt_q5_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - MOM_HOST=rabbitmq
      - MOM_PORT=5672
      - ID=0
      - AMOUNT=1
      - LEFT_INPUT_QUEUE=fetcher_output_0
      - RIGHT_INPUT_QUEUE=filtered_transfers_q5_filter
      - RIGHT_INPUT_EXCHANGE=filtered_date_and_payment_exchange
      - RIGHT_INPUT_ROUTING_KEYS=TRANSFERS_Q5_KEY
      - OUTPUT_QUEUES=filtered_to_count_q5
      - FILTER_AMOUNT=2
      - FILTER_TYPE=CONVERTED_AMOUNT_FILTER
      - QUERY_ID=5

  filter_amt_q5_1:
    build:
      context: ./src/
      dockerfile: cmd/filter/Dockerfile
    container_name: filter_amt_q5_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - MOM_HOST=rabbitmq
      - MOM_PORT=5672
      - ID=1
      - AMOUNT=1
      - LEFT_INPUT_QUEUE=fetcher_output_1
      - RIGHT_INPUT_QUEUE=filtered_transfers_q5_filter
      - RIGHT_INPUT_EXCHANGE=filtered_date_and_payment_exchange
      - RIGHT_INPUT_ROUTING_KEYS=TRANSFERS_Q5_KEY
      - OUTPUT_QUEUES=filtered_to_count_q5
      - FILTER_AMOUNT=2
      - FILTER_TYPE=CONVERTED_AMOUNT_FILTER
      - QUERY_ID=5

  count_reducer_q5:
    build:
      context: ./src/
      dockerfile: cmd/reducer/Dockerfile
    container_name: count_reducer_q5
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - MOM_HOST=rabbitmq
      - MOM_PORT=5672
      - ID=0
      - REDUCER_AMOUNT=1
      - INPUT_EOFS_EXPECTED=2
      - INPUT_QUEUE=filtered_to_count_q5
      - OUTPUT_QUEUES=results_queue
      - REDUCER_TYPE=COUNT
      - QUERY_ID=5
