services:
  rabbitmq:
    build:
      context: ./src/cmd/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    environment:
    - RABBITMQ_LOG_LEVELS=error
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
    - 5672:5672
    - 15672:15672

  gateway:
    build:
      context: ./src/
      dockerfile: cmd/gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - ACCOUNTS_EXCHANGE=accounts_exchange
    - TRANSFERS_EXCHANGE=transfers_exchange
    - RESULTS_QUEUE=results_queue
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - SERVER_HOST=gateway
    - SERVER_PORT=5678

  client_0:
    build:
      context: ./src/
      dockerfile: cmd/client/Dockerfile
    container_name: client_0
    depends_on:
    - gateway
    environment:
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    - INPUT_FILE_ACCOUNTS=/input/accounts_0.csv
    - INPUT_FILE_TRANS=/input/transactions_0.csv
    - OUTPUT_FILE_PREFIX=/output/output_0
    - MAX_BATCH_SIZE=1
    - LOG_LEVEL=DEBUG
    volumes:
    - ./input:/input
    - ./output:/output 

  filter_currency_0:
    build:
      context: ./src/
      dockerfile: cmd/filter/Dockerfile
    container_name: filter_currency_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - ID=0
    - MOM_PORT=5672
    - MOM_HOST=rabbitmq
    - INPUT_EXCHANGE=transfers_exchange
    - INPUT_QUEUE=transfers_queue
    - INPUT_ROUTING_KEYS=TRANSFERS_Q1234_KEY
    - OUTPUT_EXCHANGE=filtered_transfers_exchange
    - OUTPUT_QUEUE=filtered_transfers_q
    - OUTPUT_ROUTING_KEYS=falopa
    - CURRENCIES=US Dollar
    - FILTER_TYPE=CURRENCY

  filter_currency_1:
    build:
      context: ./src/
      dockerfile: cmd/filter/Dockerfile
    container_name: filter_currency_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - ID=1
    - MOM_PORT=5672
    - MOM_HOST=rabbitmq
    - INPUT_EXCHANGE=transfers_exchange
    - INPUT_QUEUE=transfers_queue
    - INPUT_ROUTING_KEYS=TRANSFERS_Q1234_KEY
    - OUTPUT_EXCHANGE=filtered_transfers_exchange
    - OUTPUT_QUEUE=filtered_transfers_q
    - OUTPUT_ROUTING_KEYS=falopa
    - CURRENCIES=US Dollar
    - FILTER_TYPE=CURRENCY
 
  filter_amount_0:
    build:
      context: ./src/
      dockerfile: cmd/filter/Dockerfile
    container_name: filter_amount_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - ID=0
    - MOM_PORT=5672
    - MOM_HOST=rabbitmq
    - INPUT_EXCHANGE=filtered_transfers_exchange
    - INPUT_QUEUE=filtered_transfers_q
    - INPUT_ROUTING_KEYS=falopa
    - OUTPUT_EXCHANGE=results_queue
    - OUTPUT_QUEUE=
    - OUTPUT_ROUTING_KEYS=
    - AMOUNT=50.0
    - FILTER_TYPE=AMOUNT
  
  filter_amount_1:
    build:
      context: ./src/
      dockerfile: cmd/filter/Dockerfile
    container_name: filter_amount_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - ID=1
    - MOM_PORT=5672
    - MOM_HOST=rabbitmq
    - INPUT_EXCHANGE=filtered_transfers_exchange
    - INPUT_QUEUE=filtered_transfers_q
    - INPUT_ROUTING_KEYS=falopa
    - OUTPUT_EXCHANGE=results_queue
    - OUTPUT_QUEUE=
    - INPUT_ROUTING_KEYS=
    - AMOUNT=50.0
    - FILTER_TYPE=AMOUNT